#!/usr/bin/env python3
"""Collect source-code files from public GitHub repositories.

The crawler uses GitHub's REST API to discover repositories by language, reads
each repository tree, filters likely source files, downloads text content, and
writes a JSONL manifest alongside the collected files.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import logging
import os
import random
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import quote

import requests


API_ROOT = "https://api.github.com"
RAW_ROOT = "https://raw.githubusercontent.com"
DEFAULT_API_VERSION = "2022-11-28"

PERMISSIVE_LICENSES = (
    "mit",
    "apache-2.0",
    "bsd-2-clause",
    "bsd-3-clause",
    "isc",
    "unlicense",
    "cc0-1.0",
)

LANGUAGE_CONFIG: dict[str, dict[str, Any]] = {
    "python": {"github": "Python", "extensions": (".py",)},
    "java": {"github": "Java", "extensions": (".java",)},
    "go": {"github": "Go", "extensions": (".go",)},
    "html": {"github": "HTML", "extensions": (".html", ".htm")},
    "javascript": {"github": "JavaScript", "extensions": (".js", ".jsx", ".mjs", ".cjs")},
    "typescript": {"github": "TypeScript", "extensions": (".ts", ".tsx")},
    "css": {"github": "CSS", "extensions": (".css",)},
    "c": {"github": "C", "extensions": (".c", ".h")},
    "cpp": {"github": "C++", "extensions": (".cpp", ".cc", ".cxx", ".hpp", ".hh", ".hxx")},
    "csharp": {"github": "C#", "extensions": (".cs",)},
    "php": {"github": "PHP", "extensions": (".php",)},
    "ruby": {"github": "Ruby", "extensions": (".rb",)},
    "rust": {"github": "Rust", "extensions": (".rs",)},
    "kotlin": {"github": "Kotlin", "extensions": (".kt", ".kts")},
    "swift": {"github": "Swift", "extensions": (".swift",)},
    "shell": {"github": "Shell", "extensions": (".sh", ".bash", ".zsh")},
    "sql": {"github": "SQL", "extensions": (".sql",)},
    "scala": {"github": "Scala", "extensions": (".scala",)},
    "r": {"github": "R", "extensions": (".r",)},
}

LANGUAGE_ALIASES = {
    "py": "python",
    "python3": "python",
    "js": "javascript",
    "node": "javascript",
    "ts": "typescript",
    "golang": "go",
    "c++": "cpp",
    "cc": "cpp",
    "c#": "csharp",
    "cs": "csharp",
    "bash": "shell",
    "sh": "shell",
}

SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".idea",
    ".vscode",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "venv",
    "env",
    "node_modules",
    "bower_components",
    "vendor",
    "third_party",
    "external",
    "deps",
    "dist",
    "build",
    "target",
    "out",
    "bin",
    "obj",
    "coverage",
    "site-packages",
    "generated",
}

SKIP_SUFFIXES = (
    ".min.js",
    ".min.css",
    ".bundle.js",
    ".bundle.css",
    ".pb.go",
    ".g.cs",
    ".designer.cs",
)

GENERATED_MARKERS = (
    "code generated",
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "<auto-generated",
    "@generated",
)


class GitHubError(RuntimeError):
    """Raised when a GitHub API request cannot be completed."""


@dataclass(frozen=True)
class CandidateFile:
    path: str
    size: int
    blob_sha: str
    extension: str


class GitHubClient:
    def __init__(
        self,
        token: str | None,
        timeout: float,
        api_delay: float,
        user_agent: str,
        max_retries: int,
    ) -> None:
        self.timeout = timeout
        self.api_delay = api_delay
        self.max_retries = max_retries
        self.session = requests.Session()
        self.session.headers.update(
            {
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": DEFAULT_API_VERSION,
                "User-Agent": user_agent,
            }
        )
        if token:
            self.session.headers["Authorization"] = f"Bearer {token}"

    def get_json(self, path: str, params: dict[str, Any] | None = None) -> dict[str, Any]:
        url = f"{API_ROOT}{path}"
        response = self._request("GET", url, params=params)
        try:
            payload = response.json()
        except ValueError as exc:
            raise GitHubError(f"GitHub returned non-JSON response for {url}") from exc
        if not isinstance(payload, dict):
            raise GitHubError(f"GitHub returned unexpected JSON payload for {url}")
        return payload

    def _request(
        self,
        method: str,
        url: str,
        params: dict[str, Any] | None = None,
    ) -> requests.Response:
        last_error: Exception | None = None
        for attempt in range(1, self.max_retries + 1):
            if self.api_delay > 0:
                time.sleep(self.api_delay)
            try:
                response = self.session.request(method, url, params=params, timeout=self.timeout)
            except requests.RequestException as exc:
                last_error = exc
                self._sleep_for_retry(attempt, reason=str(exc))
                continue

            if response.status_code in (403, 429):
                wait_seconds = self._rate_limit_wait(response, attempt)
                if wait_seconds is not None and attempt < self.max_retries:
                    logging.warning(
                        "GitHub rate limited request; sleeping %.1fs (%s)",
                        wait_seconds,
                        self._response_message(response),
                    )
                    time.sleep(wait_seconds)
                    continue

            if 500 <= response.status_code < 600 and attempt < self.max_retries:
                self._sleep_for_retry(attempt, reason=f"HTTP {response.status_code}")
                continue

            if response.status_code >= 400:
                raise GitHubError(
                    f"GitHub request failed: HTTP {response.status_code} {url} "
                    f"{self._response_message(response)}"
                )

            return response

        if last_error is not None:
            raise GitHubError(f"GitHub request failed after retries: {last_error}") from last_error
        raise GitHubError(f"GitHub request failed after {self.max_retries} retries: {url}")

    def _sleep_for_retry(self, attempt: int, reason: str) -> None:
        delay = min(2**attempt, 60) + random.random()
        logging.warning("Request retry in %.1fs: %s", delay, reason)
        time.sleep(delay)

    def _rate_limit_wait(self, response: requests.Response, attempt: int) -> float | None:
        retry_after = response.headers.get("Retry-After")
        if retry_after and retry_after.isdigit():
            return float(retry_after) + 1

        remaining = response.headers.get("X-RateLimit-Remaining")
        reset_at = response.headers.get("X-RateLimit-Reset")
        if remaining == "0" and reset_at and reset_at.isdigit():
            return max(1.0, float(reset_at) - time.time() + 2)

        message = self._response_message(response).lower()
        if "secondary rate limit" in message or "rate limit" in message:
            return min(60.0 * attempt, 600.0) + random.random()
        return None

    @staticmethod
    def _response_message(response: requests.Response) -> str:
        try:
            payload = response.json()
        except ValueError:
            return response.text[:300]
        message = payload.get("message") if isinstance(payload, dict) else None
        return str(message or "")[:300]


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Collect source-code files from public GitHub repositories."
    )
    parser.add_argument(
        "--languages",
        nargs="+",
        default=["python", "java", "go", "html"],
        help="Language keys or aliases. Examples: python java go html js ts cpp csharp.",
    )
    parser.add_argument("--output", default="data/github_code", help="Output directory.")
    parser.add_argument("--max-repos-per-language", type=int, default=20)
    parser.add_argument("--max-files-per-language", type=int, default=500)
    parser.add_argument("--max-files-per-repo", type=int, default=50)
    parser.add_argument("--min-stars", type=int, default=50)
    parser.add_argument("--min-bytes", type=int, default=200)
    parser.add_argument("--max-bytes", type=int, default=200_000)
    parser.add_argument("--repo-sort", default="stars", choices=["stars", "forks", "updated"])
    parser.add_argument("--order", default="desc", choices=["asc", "desc"])
    parser.add_argument("--per-page", type=int, default=100)
    parser.add_argument(
        "--license-policy",
        default="permissive",
        choices=["permissive", "any", "custom"],
        help="Default keeps common permissive licenses; use any only if you handle license review.",
    )
    parser.add_argument(
        "--licenses",
        nargs="*",
        help="GitHub license keys used when --license-policy custom is selected.",
    )
    parser.add_argument(
        "--query-extra",
        default="",
        help='Extra repository-search qualifiers, for example: "pushed:>=2025-01-01".',
    )
    parser.add_argument("--include-forks", action="store_true")
    parser.add_argument("--include-archived", action="store_true")
    parser.add_argument("--include-generated", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--seed", type=int, default=13)
    parser.add_argument("--token", default=None, help="GitHub token. Prefer --token-env for shells.")
    parser.add_argument("--token-env", default="GITHUB_TOKEN")
    parser.add_argument("--api-delay", type=float, default=0.2)
    parser.add_argument("--download-delay", type=float, default=0.0)
    parser.add_argument("--timeout", type=float, default=30.0)
    parser.add_argument("--max-retries", type=int, default=6)
    parser.add_argument("--user-agent", default="github-code-crawler/1.0")
    parser.add_argument("--log-level", default="INFO", choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    return parser.parse_args(argv)


def normalize_language(language: str) -> str:
    key = language.strip().lower()
    key = LANGUAGE_ALIASES.get(key, key)
    if key not in LANGUAGE_CONFIG:
        supported = ", ".join(sorted(LANGUAGE_CONFIG))
        raise ValueError(f"Unsupported language '{language}'. Supported: {supported}")
    return key


def license_keys_for_args(args: argparse.Namespace) -> list[str | None]:
    if args.license_policy == "any":
        return [None]
    if args.license_policy == "permissive":
        return list(PERMISSIVE_LICENSES)
    if not args.licenses:
        raise ValueError("--licenses is required when --license-policy custom is used")
    return [license_key.lower() for license_key in args.licenses]


def build_repo_query(
    language_key: str,
    license_key: str | None,
    args: argparse.Namespace,
) -> str:
    github_language = LANGUAGE_CONFIG[language_key]["github"]
    qualifiers = [
        f"language:{github_language}",
        f"stars:>={args.min_stars}",
        "is:public",
    ]
    if not args.include_archived:
        qualifiers.append("archived:false")
    if not args.include_forks:
        qualifiers.append("fork:false")
    if license_key:
        qualifiers.append(f"license:{license_key}")
    if args.query_extra:
        qualifiers.append(args.query_extra.strip())
    return " ".join(qualifiers)


def collect_repositories(
    client: GitHubClient,
    language_key: str,
    args: argparse.Namespace,
) -> list[dict[str, Any]]:
    repos: list[dict[str, Any]] = []
    seen_names: set[str] = set()
    per_page = max(1, min(args.per_page, 100))
    max_pages = max(1, 1000 // per_page)

    for license_key in license_keys_for_args(args):
        if len(repos) >= args.max_repos_per_language:
            break
        query = build_repo_query(language_key, license_key, args)
        for page in range(1, max_pages + 1):
            if len(repos) >= args.max_repos_per_language:
                break
            logging.info("Searching repos: language=%s license=%s page=%s", language_key, license_key or "any", page)
            payload = client.get_json(
                "/search/repositories",
                params={
                    "q": query,
                    "sort": args.repo_sort,
                    "order": args.order,
                    "per_page": per_page,
                    "page": page,
                },
            )
            items = payload.get("items", [])
            if not items:
                break
            for repo in items:
                full_name = repo.get("full_name")
                if not full_name or full_name in seen_names:
                    continue
                seen_names.add(full_name)
                repos.append(repo)
                if len(repos) >= args.max_repos_per_language:
                    break
            if len(items) < per_page:
                break
    return repos


def iter_candidate_files(
    client: GitHubClient,
    repo: dict[str, Any],
    language_key: str,
    args: argparse.Namespace,
) -> Iterable[CandidateFile]:
    full_name = repo["full_name"]
    default_branch = repo.get("default_branch") or "main"
    endpoint = f"/repos/{full_name}/git/trees/{quote(default_branch, safe='')}"
    payload = client.get_json(endpoint, params={"recursive": "1"})
    if payload.get("truncated"):
        logging.warning("Tree is truncated; results may be incomplete: %s", full_name)
    tree = payload.get("tree", [])
    if not isinstance(tree, list):
        return

    extensions = LANGUAGE_CONFIG[language_key]["extensions"]
    for item in tree:
        if item.get("type") != "blob":
            continue
        path = str(item.get("path") or "")
        size = int(item.get("size") or 0)
        blob_sha = str(item.get("sha") or "")
        ext = Path(path.lower()).suffix
        if ext not in extensions:
            continue
        if not should_keep_path(path, size, args):
            continue
        yield CandidateFile(path=path, size=size, blob_sha=blob_sha, extension=ext)


def should_keep_path(path: str, size: int, args: argparse.Namespace) -> bool:
    if size < args.min_bytes or size > args.max_bytes:
        return False
    lower_path = path.lower()
    if lower_path.endswith(SKIP_SUFFIXES):
        return False
    parts = [part.lower() for part in path.split("/")]
    return not any(part in SKIP_DIRS for part in parts)


def quote_path(path: str) -> str:
    return "/".join(quote(part, safe="") for part in path.split("/"))


def build_raw_url(full_name: str, ref: str, path: str) -> str:
    owner, repo = full_name.split("/", 1)
    return f"{RAW_ROOT}/{quote(owner, safe='')}/{quote(repo, safe='')}/{quote(ref, safe='')}/{quote_path(path)}"


def build_html_url(full_name: str, ref: str, path: str) -> str:
    return f"https://github.com/{full_name}/blob/{quote(ref, safe='')}/{quote_path(path)}"


def download_file(
    client: GitHubClient,
    raw_session: requests.Session,
    repo: dict[str, Any],
    candidate: CandidateFile,
    args: argparse.Namespace,
) -> tuple[bytes, str]:
    full_name = repo["full_name"]
    ref = repo.get("default_branch") or "main"
    raw_url = build_raw_url(full_name, ref, candidate.path)

    for attempt in range(1, args.max_retries + 1):
        if args.download_delay > 0:
            time.sleep(args.download_delay)
        try:
            response = raw_session.get(raw_url, timeout=args.timeout)
        except requests.RequestException as exc:
            delay = min(2**attempt, 60) + random.random()
            logging.warning("Raw download retry in %.1fs: %s", delay, exc)
            time.sleep(delay)
            continue
        if response.status_code == 200:
            return response.content, raw_url
        if response.status_code == 404:
            break
        if response.status_code in (429, 500, 502, 503, 504) and attempt < args.max_retries:
            delay = min(2**attempt, 60) + random.random()
            logging.warning("Raw download HTTP %s retry in %.1fs", response.status_code, delay)
            time.sleep(delay)
            continue
        break

    logging.debug("Falling back to contents API for %s:%s", full_name, candidate.path)
    content_endpoint = f"/repos/{full_name}/contents/{quote_path(candidate.path)}"
    payload = client.get_json(content_endpoint, params={"ref": ref})
    encoded = payload.get("content")
    encoding = payload.get("encoding")
    if encoding == "base64" and isinstance(encoded, str):
        return base64.b64decode(encoded), str(payload.get("download_url") or raw_url)
    download_url = payload.get("download_url")
    if isinstance(download_url, str):
        response = raw_session.get(download_url, timeout=args.timeout)
        if response.status_code == 200:
            return response.content, download_url
    raise GitHubError(f"Could not download {full_name}:{candidate.path}")


def decode_source(content: bytes) -> tuple[str, str] | None:
    if b"\x00" in content:
        return None
    for encoding in ("utf-8-sig", "utf-16"):
        try:
            return content.decode(encoding), encoding
        except UnicodeDecodeError:
            continue
    return content.decode("utf-8", errors="replace"), "utf-8-replace"


def is_generated_source(text: str) -> bool:
    head = "\n".join(text.splitlines()[:40]).lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def stable_file_id(repo: dict[str, Any], candidate: CandidateFile) -> str:
    key = "\0".join(
        [
            str(repo.get("full_name") or ""),
            str(repo.get("default_branch") or ""),
            candidate.path,
            candidate.blob_sha,
        ]
    )
    return hashlib.sha1(key.encode("utf-8")).hexdigest()[:24]


def load_seen(metadata_path: Path) -> tuple[set[str], set[str], set[str]]:
    seen_ids: set[str] = set()
    seen_blob_shas: set[str] = set()
    seen_content_hashes: set[str] = set()
    if not metadata_path.exists():
        return seen_ids, seen_blob_shas, seen_content_hashes

    with metadata_path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                logging.warning("Skipping invalid metadata line: %s", line[:120])
                continue
            if record.get("id"):
                seen_ids.add(str(record["id"]))
            if record.get("blob_sha"):
                seen_blob_shas.add(str(record["blob_sha"]))
            if record.get("content_sha256"):
                seen_content_hashes.add(str(record["content_sha256"]))
    return seen_ids, seen_blob_shas, seen_content_hashes


def write_record(handle: Any, record: dict[str, Any]) -> None:
    handle.write(json.dumps(record, ensure_ascii=True, sort_keys=True) + "\n")
    handle.flush()


def crawl(args: argparse.Namespace) -> dict[str, int]:
    languages = [normalize_language(language) for language in args.languages]
    token = args.token or os.getenv(args.token_env)
    if not token:
        logging.warning("No GitHub token found. Set %s to avoid very low API limits.", args.token_env)

    output_dir = Path(args.output)
    files_dir = output_dir / "files"
    metadata_path = output_dir / "metadata.jsonl"
    output_dir.mkdir(parents=True, exist_ok=True)
    files_dir.mkdir(parents=True, exist_ok=True)

    seen_ids, seen_blob_shas, seen_content_hashes = load_seen(metadata_path)
    client = GitHubClient(
        token=token,
        timeout=args.timeout,
        api_delay=args.api_delay,
        user_agent=args.user_agent,
        max_retries=args.max_retries,
    )
    raw_session = requests.Session()
    raw_session.headers.update({"User-Agent": args.user_agent})
    rng = random.Random(args.seed)
    saved_by_language: dict[str, int] = {language: 0 for language in languages}

    metadata_handle = None
    if not args.dry_run:
        metadata_handle = metadata_path.open("a", encoding="utf-8")

    try:
        for language_key in languages:
            logging.info("Collecting language: %s", language_key)
            language_dir = files_dir / language_key
            if not args.dry_run:
                language_dir.mkdir(parents=True, exist_ok=True)

            repos = collect_repositories(client, language_key, args)
            logging.info("Found %d candidate repos for %s", len(repos), language_key)

            for repo in repos:
                if saved_by_language[language_key] >= args.max_files_per_language:
                    break
                repo_saved = 0
                full_name = repo["full_name"]
                try:
                    candidates = list(iter_candidate_files(client, repo, language_key, args))
                except GitHubError as exc:
                    logging.warning("Skipping repo %s: %s", full_name, exc)
                    continue
                rng.shuffle(candidates)
                logging.info("%s has %d candidate %s files", full_name, len(candidates), language_key)

                for candidate in candidates:
                    if repo_saved >= args.max_files_per_repo:
                        break
                    if saved_by_language[language_key] >= args.max_files_per_language:
                        break
                    file_id = stable_file_id(repo, candidate)
                    if file_id in seen_ids or candidate.blob_sha in seen_blob_shas:
                        continue

                    if args.dry_run:
                        logging.info("DRY RUN keep %s:%s", full_name, candidate.path)
                        saved_by_language[language_key] += 1
                        repo_saved += 1
                        continue

                    try:
                        content, raw_url = download_file(client, raw_session, repo, candidate, args)
                    except GitHubError as exc:
                        logging.warning("Skipping file %s:%s: %s", full_name, candidate.path, exc)
                        continue

                    decoded = decode_source(content)
                    if decoded is None:
                        continue
                    text, encoding = decoded
                    if not args.include_generated and is_generated_source(text):
                        continue

                    content_sha256 = hashlib.sha256(text.encode("utf-8")).hexdigest()
                    if content_sha256 in seen_content_hashes:
                        continue

                    local_name = f"{file_id}{candidate.extension}"
                    local_path = language_dir / local_name
                    with local_path.open("w", encoding="utf-8", newline="") as source_handle:
                        source_handle.write(text)

                    license_info = repo.get("license") or {}
                    record = {
                        "id": file_id,
                        "language": language_key,
                        "github_language": LANGUAGE_CONFIG[language_key]["github"],
                        "repo_full_name": full_name,
                        "repo_url": repo.get("html_url"),
                        "repo_default_branch": repo.get("default_branch"),
                        "repo_stars": repo.get("stargazers_count"),
                        "repo_forks": repo.get("forks_count"),
                        "repo_license_key": license_info.get("key") if isinstance(license_info, dict) else None,
                        "repo_pushed_at": repo.get("pushed_at"),
                        "source_path": candidate.path,
                        "source_url": build_html_url(full_name, repo.get("default_branch") or "main", candidate.path),
                        "raw_url": raw_url,
                        "blob_sha": candidate.blob_sha,
                        "source_size_bytes": candidate.size,
                        "local_path": str(local_path.relative_to(output_dir)),
                        "encoding": encoding,
                        "content_sha256": content_sha256,
                        "downloaded_at": datetime.now(timezone.utc).isoformat(),
                    }
                    write_record(metadata_handle, record)
                    seen_ids.add(file_id)
                    seen_blob_shas.add(candidate.blob_sha)
                    seen_content_hashes.add(content_sha256)
                    saved_by_language[language_key] += 1
                    repo_saved += 1

                logging.info("Saved %d files from %s", repo_saved, full_name)
    finally:
        if metadata_handle is not None:
            metadata_handle.close()

    return saved_by_language


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s %(levelname)s %(message)s",
    )
    try:
        saved = crawl(args)
    except (GitHubError, ValueError) as exc:
        logging.error("%s", exc)
        return 1

    label = "Would collect" if args.dry_run else "Collected"
    for language, count in saved.items():
        logging.info("%s %d files for %s", label, count, language)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
